# netlify.toml (ra√≠z del repo)
[build]
  base    = "tech-farming-frontend"
  command = "npm ci && npm run build -- --configuration=production"
  publish = "dist/tech-farming-frontend"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200